AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  PayGasX Bundler server

Globals:
  Function:
    Timeout: 10
    #Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  Bundler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda
      Runtime: go1.x
      MemorySize: 128
      Architectures:
        - x86_64
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref Configuration
      Environment:
        Variables:
          SECRET_NAME: !Ref Configuration
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: "2.0"
            Path: /
            Method: ANY
  Configuration:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: PayGasX Bundler server configuration
      GenerateSecretString:
        PasswordLength: 64

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BundlerAPI:
    Description: "API Gateway endpoint URL for Prod environment for Bundler function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
